### ISSUE TITLE
피드백(박진효)

### ISSUE THREAD

**Issue by csp61** [syKim12/like-lion#1]
수연님! musichome.html 이외에는 해당 주제와 관련없는 파일들이므로 해당 파일들은 업로드 안해주셔도 됩니다! 혹은 동일 레포 안에 계속 올리고 싶으시면 1주차, 2주차 폴더 이런식으로 만들어주셔서 구분해주시는 것이 좋습니다!

**Comment by syKim12** [comment]
폴더 만들어서 정리했습니다!ㅎㅎ 피드백 감사드려요 :)
